### ISSUE TITLE
Modules not installed

### ISSUE THREAD

**Issue by 13lackWidow** [SimplySecurity/SimplyEmail#41]
## SimplyEmail Version
Latest

## OS Information (Linux flavor, Python version)
Kali Linux, latest

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Modules not installed after running the one-line installer or the multi-line setup.

## Screenshot of error, embedded text output, or Pastebin link to the error
ImportError: No module named fake_useragent
ImportError: No module named docx2txt
ImportError: No module named pdfminer.pdfinterp

## Any additional information
Solution: You need to pip install fake-useragent, docx2txt, and pdfminer manually.
(Run: "pip install fake-useragent docx2txt pdfminer" )

**Comment by killswitch-GUI** [comment]
@13lackWidow that's really interesting since https://github.com/SimplySecurity/SimplyEmail/blob/master/setup/requirments.txt has two of the three. Also thanks for the heads up I somehow missed fake_useragent, may need to add that to the tests :)

**Comment by killswitch-GUI** [comment]
Full docker images are now available post version 1.4.5, setup script has been updates and CI runners are passing on Debian/Kali, and Ubuntu. Please let me know if any other issues come up.
