### ISSUE TITLE
[Hunter] Missing/Incomplete results

### ISSUE THREAD

**Issue by whoot** [SimplySecurity/SimplyEmail#57]
## SimplyEmail Version
Current Version: v1.5.0 

## OS Information (Linux flavor, Python version)
python -V
Python 2.7.15+

uname -a
Linux kali 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

SimplyMail does not catch all results from the Hunter API. 

Example:
```
python2 SimplyEmail.py -e mgm-tp.com -t Hunter

============================================================
 Current Version: v1.5.0 | Website: CyberSyndicates.com
 ============================================================
 Twitter: @real_slacker007 |  Twitter: @Killswitch_gui
 ============================================================
 [*] Email reconnaissance has been completed:

   File Location: 		/opt/simplyemail/mgm-tp.com-20180911-1255
   Unique Emails Found:		18
   Emails Built from Names:	0
   Total Emails:		18
```
When I request the API directly in the browser, I get all results:

```
https://api.hunter.io/v2/domain-search?domain=mgm-tp.com&api_key=xxxxxxx

[...]
 "meta": {
    "results": 31,
```

**Comment by capnspacehook** [comment]
Look in the config file... If I remember correctly the Hunter module by default only grabs personal emails, not generic ones. Change that option and the config and run the module again and see if it returns any more emails.

**Comment by whoot** [comment]
Thank you for that hint! Using 'Both' gives me all email addresses.

However, could you please adjust the Config file? It states, that you have to use 'generic' or 'both'.
But using these will result in an error ( [*] Error in Hunter settings: Email Type setting invalid).
You have to use '**B**oth' or '**G**eneric'.

The same applies to the help output. It states that you have use '-t html / flickr / google'.
However, using these results in a silent fail (No emails found), but using them with an upper case (Html / Flickr / Google), they work as expected.
